[project]
authors = ["cmrivera8 <carlos.rivera8528@hotmail.com>"]
channels = ["conda-forge"]
description = "Tool for analyzing stability and evaluating the contributions of experimental parameters."
name = "StabilityFusion"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[pypi-dependencies]
engineering_notation = "*"
python-datemath = "*"

[dependencies]
python = "*"
pyqt = ">=5.15.9,<6"
pyqtgraph = ">=0.13.7,<0.14"
numpy = ">=2.1.3,<3"
pandas = ">=2.2.3,<3"
influxdb-client = ">=1.46.0,<2"
scipy = "*"
tqdm = "*"
bottleneck = "*"
allantools = "*"
aiohttp = "*"
aiocsv = "*"